<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <WarningsAsErrors>$(WarningsAsErrors);IDE0161</WarningsAsErrors>
  </PropertyGroup>

  <!-- Plugin specific properties -->
  <PropertyGroup>
    <Product>Dash Evolution</Product>
    <Description>This plugin extends BTCPay Server to enable users to receive payments via Dash on the Evolution Platform (shielded Orchard pool and Platform Addresses).</Description>
    <Version>1.0.0</Version>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <!-- Plugin development properties -->
  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <TargetFrameworkMonikerAssemblyAttributesPath>$([System.IO.Path]::Combine('$(IntermediateOutputPath)','$(TargetFrameworkMoniker).AssemblyAttributes$(DefaultLanguageSourceExtension)'))</TargetFrameworkMonikerAssemblyAttributesPath>
  </PropertyGroup>

  <!-- This will make sure that referencing BTCPayServer doesn't put any artifact in the published directory -->
  <ItemDefinitionGroup>
    <ProjectReference>
      <Properties>StaticWebAssetsEnabled=false</Properties>
      <Private>false</Private>
      <ExcludeAssets>runtime;native;build;buildTransitive;contentFiles</ExcludeAssets>
    </ProjectReference>
  </ItemDefinitionGroup>

  <!-- Workaround for https://github.com/dotnet/roslyn/issues/41640 -->
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS1573</NoWarn>
  </PropertyGroup>

  <!-- Deterministic build -->
  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.39" PrivateAssets="All"/>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.202" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Update="BTCPayServer.Plugins.DashEvolution.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\submodules\btcpayserver\BTCPayServer\BTCPayServer.csproj" />
  </ItemGroup>
</Project>
